AY1920S1-CS2113T-F09-4/main

- data/todo_list.txt
- src/main/java/duke/DukeException.java
- src/main/java/duke/Parser.java
- src/main/java/duke/Storage.java
- src/main/java/duke/Ui.java
- src/main/java/duke/commands/AddCommand.java
- src/main/java/duke/tasks/BetweenTask.java
- src/main/java/duke/tasks/RecurringTask.java
- src/test/java/duke/tasks/BetweenTaskTest.java
- src/test/java/duke/tasks/RecurringTaskTest.java
DoWitihinPeriodTasks: provided support for managing tasks that need to be done within a certain period with the class BetweenTask.
RecurringTasks: Provided support for managing recurring tasks with the class RecurringTask.
> B-DoWithinPeriodTasks: Time bound tasks and B-RecurringTasks: Recurring Tasks

- src/main/java/duke/DukeException.java
- src/main/java/duke/Parser.java
- src/main/java/duke/Ui.java
- src/main/java/duke/commands/AddBarCommand.java
- src/main/java/duke/commands/Command.java
- src/main/java/duke/commands/HelpCommand.java
- src/main/java/duke/commands/NewCommand.java
- src/main/java/duke/commands/ViewCommand.java
Add first basic implementation of the song commands.
> Add AddBarCommand, HelpCommand, NewCommand and ViewCommand classes

- src/main/java/duke/Duke.java
- src/main/java/duke/TaskList.java
- src/main/java/duke/Ui.java
- src/main/java/duke/commands/AddBarCommand.java
- src/main/java/duke/commands/AddCommand.java
- src/main/java/duke/commands/ByeCommand.java
- src/main/java/duke/commands/Command.java
- src/main/java/duke/commands/DeleteCommand.java
- src/main/java/duke/commands/DoneCommand.java
- src/main/java/duke/commands/FindCommand.java
- src/main/java/duke/commands/HelpCommand.java
- src/main/java/duke/commands/ListCommand.java
- src/main/java/duke/commands/NewCommand.java
- src/main/java/duke/commands/RemindCommand.java
- src/main/java/duke/commands/ViewCommand.java
- src/main/java/duke/components/SongList.java
Implement the SongList class to store the Song list and perform manipulations to the list.
> Add SongList class

- src/main/java/duke/Duke.java
- src/main/java/duke/DukeException.java
- src/main/java/duke/Parser.java
- src/main/java/duke/Ui.java
- src/main/java/duke/commands/CopyCommand.java
- src/main/java/duke/commands/GroupCommand.java
- src/main/java/duke/commands/RemindCommand.java
Created the base code for GroupCommand and CopyCommand
> Base code for Group Command and Copy Command

- src/main/java/duke/Storage.java
> Plan Storage class and include basic functions

- src/main/java/duke/Duke.java
- src/main/java/duke/DukeException.java
- src/main/java/duke/Parser.java
- src/main/java/duke/Ui.java
- src/main/java/duke/commands/AddOverlayCommand.java
- src/main/java/duke/components/Note.java
@Samuel787 @rohan-av @SalonetheGreat @jwyf
> overlay added

- src/main/java/duke/commands/CopyCommand.java
- src/main/java/duke/commands/GroupCommand.java
- src/main/java/duke/components/Group.java
- src/main/java/duke/components/Song.java
- src/main/java/duke/components/VerseList.java
On top of completing these commands, also added some public methods to Song class and added VerseList class (to contain a list of all the Verses the user makes)
> Completed Copy and Group Command

- src/main/java/duke/commands/AddOverlayCommand.java
- src/main/java/duke/components/Bar.java
- src/main/java/duke/components/Song.java
@Samuel787 @rohan-av @SalonetheGreat @jwyf
> This is the overlay function added

- src/main/java/duke/Parser.java
- src/main/java/duke/Ui.java
- src/main/java/duke/commands/CommandSyntaxMessage.java
- src/main/java/duke/commands/HelpCommand.java
1. Add a CommandSyntaxMessage Class to store all the formats of commands
2. Implement HelpCommand
3. Change complex if-else in Parser to Switch
> HelpCommand

- src/main/java/duke/Storage.java
- src/main/java/duke/commands/NewCommand.java
- src/main/java/duke/components/Bar.java
- src/main/java/duke/components/Chord.java
- src/main/java/duke/components/Group.java
- src/main/java/duke/components/Note.java
- src/main/java/duke/components/Pitch.java
- src/main/java/duke/components/Song.java
> Fix bug in toString functions

- src/main/java/duke/Duke.java
- src/main/java/duke/DukeException.java
- src/main/java/duke/Storage.java
- src/main/java/duke/Ui.java
- src/main/java/duke/commands/AddOverlayCommand.java
- src/main/java/duke/commands/ListCommand.java
- src/main/java/duke/components/Bar.java
- src/main/java/duke/components/Note.java
- src/main/java/duke/components/Song.java
> Finish implementing Storage functionality

- src/main/java/duke/DukeException.java
- src/main/java/duke/Parser.java
- src/main/java/duke/commands/AddBarCommand.java
- src/main/java/duke/components/Bar.java
> Fix issues regarding Bar length validation for AddBar and improved exception handling

- data/todo_list.txt
- src/main/java/duke/Duke.java
- src/main/java/duke/commands/AddOverlayCommand.java
@Samuel787 @rohan-av @SalonetheGreat @jwyf
> Created the ability to overlay to a specific bar

- src/main/java/duke/Duke.java
@Samuel787 @rohan-av @SalonetheGreat @jwyf
> changed directory of storage

- src/main/java/duke/Duke.java
- src/main/java/duke/DukeException.java
- src/main/java/duke/commands/AsciiCommand.java
- src/main/java/duke/commands/CopyCommand.java
- src/main/java/duke/commands/GroupCommand.java
- src/main/java/duke/components/VerseList.java
AsciiCommand now extends Command<SongList> and hence it can function well with the rest of the application
> Ascii Command Done Up (Minor bug fixed)

- data/todo_list.txt
- src/main/java/duke/Storage.java
- src/main/java/duke/commands/AddBarCommand.java
- src/main/java/duke/components/Bar.java
- src/main/java/duke/components/Note.java
- src/test/java/duke/components/BarTest.java
- src/test/java/duke/components/ChordTest.java
- src/test/java/duke/components/NoteTest.java
- src/test/java/duke/components/SongTest.java
Includes test code for the following classes:
- Song
- Bar
- Note
- Chord
**NOTE:** There are test methods not yet implemented. For those who worked on the specific methods, please add the appropriate test methods in the test files, as suggested by the todo markers in the comments of each file.
Works towards the completion of #111
> Add JUnit test code for components

- src/main/java/duke/Duke.java
- src/main/java/duke/DukeException.java
- src/main/java/duke/Parser.java
- src/main/java/duke/Ui.java
- src/main/java/duke/commands/AddBarCommand.java
- src/main/java/duke/commands/DeleteBarCommand.java
- src/main/java/duke/commands/DeleteCommand.java
- src/main/java/duke/commands/EditCommand.java
- src/main/java/duke/commands/NewCommand.java
- src/main/java/duke/commands/ViewCommand.java
- src/main/java/duke/components/SongList.java
Add ui & storage support and Complete ViewCommand, AddBarCommand, NewCommand, EditCommand, DeleteCommand and DeleteBarCommand
#119 #82
> Complete CRUD commands

- data/todo_list.txt
- src/main/java/duke/Duke.java
- src/main/java/duke/Parser.java
- src/main/java/duke/Ui.java
- src/main/java/duke/commands/AddBarCommand.java
- src/main/java/duke/commands/AddOverlayCommand.java
- src/main/java/duke/commands/ByeCommand.java
- src/main/java/duke/commands/Command.java
- src/main/java/duke/commands/CommandSyntaxMessage.java
- src/main/java/duke/commands/CopyCommand.java
- src/main/java/duke/commands/HelpCommand.java
- src/main/java/duke/commands/ListCommand.java
- src/main/java/duke/commands/RedoCommand.java
- src/main/java/duke/commands/UndoCommand.java
- src/main/java/duke/components/SongList.java
- src/main/java/duke/components/UndoRedoStack.java
Add UndoCommand
Add RedoCommand
Add UndoRedoStack
> Add a basic VCS(Version Control System)

- src/main/java/ducats/Ducats.java
- src/main/java/ducats/Metronome.java
- src/main/java/ducats/Parser.java
- src/main/java/ducats/Ui.java
- src/main/java/ducats/commands/AddBarCommand.java
- src/main/java/ducats/commands/AddOverlayCommand.java
- src/main/java/ducats/commands/AsciiCommand.java
- src/main/java/ducats/commands/ByeCommand.java
- src/main/java/ducats/commands/Command.java
- src/main/java/ducats/commands/CommandSyntaxMessage.java
- src/main/java/ducats/commands/CopyCommand.java
- src/main/java/ducats/commands/DeleteBarCommand.java
- src/main/java/ducats/commands/DeleteCommand.java
- src/main/java/ducats/commands/EditCommand.java
- src/main/java/ducats/commands/GroupCommand.java
- src/main/java/ducats/commands/HelpCommand.java
- src/main/java/ducats/commands/ListCommand.java
- src/main/java/ducats/commands/MetronomeCommand.java
- src/main/java/ducats/commands/NewCommand.java
- src/main/java/ducats/commands/OverlayBarGroup.java
- src/main/java/ducats/commands/OverlayBarSong.java
- src/main/java/ducats/commands/OverlayGroupGroup.java
- src/main/java/ducats/commands/RedoCommand.java
- src/main/java/ducats/commands/UndoCommand.java
- src/main/java/ducats/commands/ViewCommand.java
> Add Metronome feature

- src/main/java/ducats/Ducats.java
- src/main/java/ducats/Parser.java
- src/main/java/ducats/Ui.java
- src/main/java/ducats/commands/AddOverlayCommand.java
- src/main/java/ducats/commands/OverlayBarGroup.java
- src/main/java/ducats/commands/OverlayBarSong.java
- src/main/java/ducats/commands/OverlayGroupGroup.java
- src/main/java/ducats/components/WordGetter.java
- src/test/main/java/ducats/components/OverlayGroupGroupTest.java
@Samuel787 @rohan-av @jwyf @SalonetheGreat
> fixed bugs

- src/main/java/ducats/DucatsException.java
- src/main/java/ducats/commands/NewCommand.java
- src/main/java/ducats/components/SongList.java
Fixes all bugs related to unintended creation of songs with exact same names.
(Fixes #198, #197, #187, #180, #179, #167)
> Create new exception to prevent same song names

- src/main/java/ducats/Storage.java
Removed unnecessary code as well.
> Updated Storage to include JavaDocs

- .gitignore
- src/main/java/ducats/Ducats.java
- src/main/java/ducats/DucatsLogger.java
- src/main/java/ducats/Metronome.java
- src/main/java/ducats/Parser.java
- src/main/java/ducats/Storage.java
- src/main/java/ducats/commands/ListCommand.java
- src/main/java/ducats/commands/OpenCommand.java
Integrating the logger with your own code is easy. Simply import the DucatsLogger class and use the appropriate level to log what happens. (E.g. DucatsLogger.severe("oof!!") will add the Severe level message "oof!!" to the log)
> Implement Logging functionality

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
Created structure for UG adoc, and shifted over some content.
Made progress in the DG (Metronome).
> Update UG and DG
